### ISSUE TITLE
UIMain.cpp and main.cpp are duplicate files

### ISSUE THREAD

**Issue by burtonwilliamt** [rohitrango/StegoTool#2]
It looks like main.cpp and UImain.cpp are the same file. When I tried to compile on my computer, I just used *.cpp initially, and it caused a linker error because both files have a main function. Any reason both exist?

**Comment by burtonwilliamt** [comment]
Also, would there be any interest in a Makefile? It would make it easier for other people to compile the code.

**Comment by rohitrango** [comment]
Yes. You can remove either one of them. Plus, a makefile would be nice to use.
